# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "28b6d16c-2808-4bda-b486-5e6b83de9ef2"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  gradle(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "8c5129c2e78aac330db4577170707615bcde23b5",
    build_secret: "e62aeeae55baa5afe06bc595e6a570bad408b940765e62275675638d79960aeb"
  )
end
